version: '3.7'
services:

  mongo:
    image: mongo:4.1-bionic
    volumes:
      - ./data:/data/db
    expose:
      - 27017
 
  app:
    build: .
    image: swapi-api-image:1.0
    restart: always
    environment:
      MONGO_URL: mongodb://mongo/swapi
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
    ports:
      - 3000:3000